### ISSUE TITLE
roslaunch sound_classification save_noise_sound.launch の挙動について

### ISSUE THREAD

**Issue by ayfujii** [708yamaguchi/sound_classification#1]
下記のようなメッセージが出るのですが、正しく終わっているという認識で大丈夫でしょうか？

roslaunch sound_classification save_noise_sound.launch
... logging to /home/a-fujii/.ros/log/73589ca0-b772-11e9-a738-e86a64b6d6bb/roslaunch-afujii-ThinkPad-T480-1826.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
started roslaunch server http://192.168.97.116:41529/
SUMMARY

PARAMETERS
 * /classify_spectrogram_ros/model: /home/a-fujii/aud...
 * /microphone/length: 512
 * /microphone/name: default
 * /microphone/rate: 44100
 * /publish_spectrogram/cutoff_rate: 8000
 * /publish_spectrogram/hit_volume_threshold: 0.1
 * /publish_spectrogram/time_to_listen: 0.3
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    listen_microphone (sound_classification/listen_microphone.py)
    publish_spectrogram (sound_classification/publish_spectrogram.py)
    save_noise_sound (sound_classification/save_noise_sound.py)

ROS_MASTER_URI=http://localhost:11311

process[listen_microphone-1]: started with pid [1853]
process[publish_spectrogram-2]: started with pid [1854]
process[save_noise_sound-3]: started with pid [1855]
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
[INFO] [1565011366.896383]: frequency list of fft:
[  86.1328125  172.265625   258.3984375  344.53125    430.6640625
  516.796875   602.9296875  689.0625     775.1953125  861.328125
  947.4609375 1033.59375   1119.7265625 1205.859375  1291.9921875
 1378.125     1464.2578125 1550.390625  1636.5234375 1722.65625
 1808.7890625 1894.921875  1981.0546875 2067.1875    2153.3203125
 2239.453125  2325.5859375 2411.71875   2497.8515625 2583.984375
 2670.1171875 2756.25      2842.3828125 2928.515625  3014.6484375
 3100.78125   3186.9140625 3273.046875  3359.1796875 3445.3125
 3531.4453125 3617.578125  3703.7109375 3789.84375   3875.9765625
 3962.109375  4048.2421875 4134.375     4220.5078125 4306.640625
 4392.7734375 4478.90625   4565.0390625 4651.171875  4737.3046875
 4823.4375    4909.5703125 4995.703125  5081.8359375 5167.96875
 5254.1015625 5340.234375  5426.3671875 5512.5       5598.6328125
 5684.765625  5770.8984375 5857.03125   5943.1640625 6029.296875
 6115.4296875 6201.5625    6287.6953125 6373.828125  6459.9609375
 6546.09375   6632.2265625 6718.359375  6804.4921875 6890.625
 6976.7578125 7062.890625  7149.0234375 7235.15625   7321.2890625
 7407.421875  7493.5546875 7579.6875    7665.8203125 7751.953125
 7838.0859375 7924.21875  ]
/home/a-fujii/audio_ws/src/sound_classification/scripts/publish_spectrogram.py:42: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  '/microphone/spectrogram', Image)
/home/a-fujii/audio_ws/src/sound_classification/scripts/publish_spectrogram.py:44: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  '/microphone/hit_spectrogram', Image)
[WARN] [1565011368.416748]: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[INFO] [1565011370.035249]: Record 3.0 seconds
[INFO] [1565011370.035510]: Saved /home/a-fujii/audio_ws/src/sound_classification/scripts/mean_noise_sound.npy

REQUIRED process [save_noise_sound-3] has died!
process has finished cleanly
log file: /home/a-fujii/.ros/log/73589ca0-b772-11e9-a738-e86a64b6d6bb/save_noise_sound-3*.log
Initiating shutdown!

[save_noise_sound-3] killing on exit
[publish_spectrogram-2] killing on exit
[listen_microphone-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by 708yamaguchi** [comment]
以下の部分が赤字（Error）になって紛らわしかったです。すみません。
```
REQUIRED process [save_noise_sound-3] has died!
process has finished cleanly
log file: /home/a-fujii/.ros/log/73589ca0-b772-11e9-a738-e86a64b6d6bb/save_noise_sound-3*.log
Initiating shutdown!
```

僕のプログラムとしては、周囲のノイズを保存するプログラム(save_noise_sound.py)が3秒間音を記録したら勝手に死ぬようにしていて、それに伴ってroslaunch全体が死ぬようにしていました(requiredタグを使っています)。
ただこの使い方をすると、先ほどの赤字のエラーメッセージがシェル上に吐かれてしまうようです。
https://github.com/ros/ros_comm/blob/cd1faed42d2be63ebeee270fdd362a07485b0bb4/tools/roslaunch/src/roslaunch/pmon.py#L567

赤い文字が吐かれるのは混乱を招くと思いますので、周囲のノイズを保存するプログラムが3秒間音を記録したら、ユーザ側にCtrl-Cを押してもらうように誘導しようと思います。
![program_end_message](https://user-images.githubusercontent.com/19769486/62471367-89d80c80-b7d7-11e9-9f5a-628db224fcec.png)

ありがとうございました。

**Comment by 708yamaguchi** [comment]
以下のコミットで直しました。
https://github.com/708yamaguchi/sound_classification/commit/4cf39a2d0c0811a03a4dfa43f6ef458f8782297d
