### ISSUE TITLE
classify sound from /audio (AudioData.msg) 

### ISSUE THREAD

**Issue by ykawamura96** [708yamaguchi/sound_classification#6]
I'm currently using this package with HRP2. Since there's no default microphone with the HRP2, I attached USB microphne to on-board computer then I launch `listen_microphone.launch`  in on the computer. (roscore is running in the on-board computer). 

But in near future, when the robot has default microphone and start publishing `/audio`, I think this package should have option to use `/audio` topic instead of launching `listen_microphone.launch`.

**Comment by 708yamaguchi** [comment]
I think your idea is important, too.

Currently, I am trying to publish spectrogram topic from `/audio` topic.
https://github.com/jsk-ros-pkg/jsk_recognition/pull/ 2478

Please wait for a while.

**Comment by 708yamaguchi** [comment]
Sorry for late.
I updated using `/audio` topic.
